CREATE DATABASE ic;
USE ic;
CREATE TABLE ic_data (name_card varchar(40), text1 text, text2 text, img varchar(100));

INSERT INTO `ic_data`(`name_card`, `text1`, `text2`, `img`) VALUES ("Projeto 1","Lorem ipsum dolor sit amet","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget pulvinar nisi. In tellus augue, posuere non massa eget, molestie dictum velit. Phasellus gravida augue metus, sit amet bibendum lorem ullamcorper sit amet. Mauris dui arcu, placerat vel iaculis non, sodales at sapien. In convallis libero sed orci convallis elementum. Sed id consectetur sem. Etiam ultrices ante a porta vehicula. Donec sem justo, viverra sit amet finibus eu, condimentum quis mi. In eu dolor leo. Sed lacus nibh, faucibus vel orci in, luctus condimentum sem.

Donec nec lectus suscipit, aliquet dui et, porta sem. Nunc sit amet blandit massa, vitae mollis magna. Nunc eget suscipit ligula, non auctor nulla. Donec dui dui, posuere ac volutpat id, consequat in tellus. Donec quis nibh in enim tristique commodo in ut orci. Etiam convallis turpis venenatis odio imperdiet, at hendrerit elit feugiat. Curabitur nec bibendum erat, eu mollis libero. Quisque a est id elit tempor porttitor ullamcorper at mauris. Vivamus rutrum, diam sit amet vestibulum auctor, est felis suscipit ligula, vitae convallis dolor diam sit amet mauris. Nullam ac eros nec nibh sollicitudin rhoncus. Nunc tempor ornare vehicula. Duis vehicula lectus eget diam convallis placerat. Donec tellus risus, tempor id posuere nec, luctus nec odio. Nulla nec commodo tortor.

Vivamus massa nisi, mattis a venenatis et, gravida vulputate lectus. Aliquam nec lobortis ligula. Mauris ullamcorper vehicula dui in varius. Sed orci eros, tempus non arcu eu, dignissim aliquam sem. Integer tempus fermentum lectus, non volutpat massa bibendum nec. Vestibulum in mi quis sem auctor luctus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam eleifend euismod arcu, non dapibus leo varius et. Mauris eu lacinia nulla. Aliquam suscipit pulvinar mattis. Aliquam sed tincidunt nunc, at cursus justo.", "https://images.pexels.com/photos/546819/pexels-photo-546819.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260"),

("Projeto 2","Lorem ipsum dolor sit amet","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget pulvinar nisi. In tellus augue, posuere non massa eget, molestie dictum velit. Phasellus gravida augue metus, sit amet bibendum lorem ullamcorper sit amet. Mauris dui arcu, placerat vel iaculis non, sodales at sapien. In convallis libero sed orci convallis elementum. Sed id consectetur sem. Etiam ultrices ante a porta vehicula. Donec sem justo, viverra sit amet finibus eu, condimentum quis mi. In eu dolor leo. Sed lacus nibh, faucibus vel orci in, luctus condimentum sem.

Donec nec lectus suscipit, aliquet dui et, porta sem. Nunc sit amet blandit massa, vitae mollis magna. Nunc eget suscipit ligula, non auctor nulla. Donec dui dui, posuere ac volutpat id, consequat in tellus. Donec quis nibh in enim tristique commodo in ut orci. Etiam convallis turpis venenatis odio imperdiet, at hendrerit elit feugiat. Curabitur nec bibendum erat, eu mollis libero. Quisque a est id elit tempor porttitor ullamcorper at mauris. Vivamus rutrum, diam sit amet vestibulum auctor, est felis suscipit ligula, vitae convallis dolor diam sit amet mauris. Nullam ac eros nec nibh sollicitudin rhoncus. Nunc tempor ornare vehicula. Duis vehicula lectus eget diam convallis placerat. Donec tellus risus, tempor id posuere nec, luctus nec odio. Nulla nec commodo tortor.

Vivamus massa nisi, mattis a venenatis et, gravida vulputate lectus. Aliquam nec lobortis ligula. Mauris ullamcorper vehicula dui in varius. Sed orci eros, tempus non arcu eu, dignissim aliquam sem. Integer tempus fermentum lectus, non volutpat massa bibendum nec. Vestibulum in mi quis sem auctor luctus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam eleifend euismod arcu, non dapibus leo varius et. Mauris eu lacinia nulla. Aliquam suscipit pulvinar mattis. Aliquam sed tincidunt nunc, at cursus justo.", "https://images.pexels.com/photos/2148217/pexels-photo-2148217.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260"),
("Projeto 3","Lorem ipsum dolor sit amet","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget pulvinar nisi. In tellus augue, posuere non massa eget, molestie dictum velit. Phasellus gravida augue metus, sit amet bibendum lorem ullamcorper sit amet. Mauris dui arcu, placerat vel iaculis non, sodales at sapien. In convallis libero sed orci convallis elementum. Sed id consectetur sem. Etiam ultrices ante a porta vehicula. Donec sem justo, viverra sit amet finibus eu, condimentum quis mi. In eu dolor leo. Sed lacus nibh, faucibus vel orci in, luctus condimentum sem.

Donec nec lectus suscipit, aliquet dui et, porta sem. Nunc sit amet blandit massa, vitae mollis magna. Nunc eget suscipit ligula, non auctor nulla. Donec dui dui, posuere ac volutpat id, consequat in tellus. Donec quis nibh in enim tristique commodo in ut orci. Etiam convallis turpis venenatis odio imperdiet, at hendrerit elit feugiat. Curabitur nec bibendum erat, eu mollis libero. Quisque a est id elit tempor porttitor ullamcorper at mauris. Vivamus rutrum, diam sit amet vestibulum auctor, est felis suscipit ligula, vitae convallis dolor diam sit amet mauris. Nullam ac eros nec nibh sollicitudin rhoncus. Nunc tempor ornare vehicula. Duis vehicula lectus eget diam convallis placerat. Donec tellus risus, tempor id posuere nec, luctus nec odio. Nulla nec commodo tortor.

Vivamus massa nisi, mattis a venenatis et, gravida vulputate lectus. Aliquam nec lobortis ligula. Mauris ullamcorper vehicula dui in varius. Sed orci eros, tempus non arcu eu, dignissim aliquam sem. Integer tempus fermentum lectus, non volutpat massa bibendum nec. Vestibulum in mi quis sem auctor luctus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam eleifend euismod arcu, non dapibus leo varius et. Mauris eu lacinia nulla. Aliquam suscipit pulvinar mattis. Aliquam sed tincidunt nunc, at cursus justo.", "https://images.pexels.com/photos/2136243/pexels-photo-2136243.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260"),

("Projeto 4","Lorem ipsum dolor sit amet","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget pulvinar nisi. In tellus augue, posuere non massa eget, molestie dictum velit. Phasellus gravida augue metus, sit amet bibendum lorem ullamcorper sit amet. Mauris dui arcu, placerat vel iaculis non, sodales at sapien. In convallis libero sed orci convallis elementum. Sed id consectetur sem. Etiam ultrices ante a porta vehicula. Donec sem justo, viverra sit amet finibus eu, condimentum quis mi. In eu dolor leo. Sed lacus nibh, faucibus vel orci in, luctus condimentum sem.

Donec nec lectus suscipit, aliquet dui et, porta sem. Nunc sit amet blandit massa, vitae mollis magna. Nunc eget suscipit ligula, non auctor nulla. Donec dui dui, posuere ac volutpat id, consequat in tellus. Donec quis nibh in enim tristique commodo in ut orci. Etiam convallis turpis venenatis odio imperdiet, at hendrerit elit feugiat. Curabitur nec bibendum erat, eu mollis libero. Quisque a est id elit tempor porttitor ullamcorper at mauris. Vivamus rutrum, diam sit amet vestibulum auctor, est felis suscipit ligula, vitae convallis dolor diam sit amet mauris. Nullam ac eros nec nibh sollicitudin rhoncus. Nunc tempor ornare vehicula. Duis vehicula lectus eget diam convallis placerat. Donec tellus risus, tempor id posuere nec, luctus nec odio. Nulla nec commodo tortor.

Vivamus massa nisi, mattis a venenatis et, gravida vulputate lectus. Aliquam nec lobortis ligula. Mauris ullamcorper vehicula dui in varius. Sed orci eros, tempus non arcu eu, dignissim aliquam sem. Integer tempus fermentum lectus, non volutpat massa bibendum nec. Vestibulum in mi quis sem auctor luctus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam eleifend euismod arcu, non dapibus leo varius et. Mauris eu lacinia nulla. Aliquam suscipit pulvinar mattis. Aliquam sed tincidunt nunc, at cursus justo.", "https://images.pexels.com/photos/1148820/pexels-photo-1148820.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260"),

("Projeto 5","Lorem ipsum dolor sit amet","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget pulvinar nisi. In tellus augue, posuere non massa eget, molestie dictum velit. Phasellus gravida augue metus, sit amet bibendum lorem ullamcorper sit amet. Mauris dui arcu, placerat vel iaculis non, sodales at sapien. In convallis libero sed orci convallis elementum. Sed id consectetur sem. Etiam ultrices ante a porta vehicula. Donec sem justo, viverra sit amet finibus eu, condimentum quis mi. In eu dolor leo. Sed lacus nibh, faucibus vel orci in, luctus condimentum sem.

Donec nec lectus suscipit, aliquet dui et, porta sem. Nunc sit amet blandit massa, vitae mollis magna. Nunc eget suscipit ligula, non auctor nulla. Donec dui dui, posuere ac volutpat id, consequat in tellus. Donec quis nibh in enim tristique commodo in ut orci. Etiam convallis turpis venenatis odio imperdiet, at hendrerit elit feugiat. Curabitur nec bibendum erat, eu mollis libero. Quisque a est id elit tempor porttitor ullamcorper at mauris. Vivamus rutrum, diam sit amet vestibulum auctor, est felis suscipit ligula, vitae convallis dolor diam sit amet mauris. Nullam ac eros nec nibh sollicitudin rhoncus. Nunc tempor ornare vehicula. Duis vehicula lectus eget diam convallis placerat. Donec tellus risus, tempor id posuere nec, luctus nec odio. Nulla nec commodo tortor.

Vivamus massa nisi, mattis a venenatis et, gravida vulputate lectus. Aliquam nec lobortis ligula. Mauris ullamcorper vehicula dui in varius. Sed orci eros, tempus non arcu eu, dignissim aliquam sem. Integer tempus fermentum lectus, non volutpat massa bibendum nec. Vestibulum in mi quis sem auctor luctus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam eleifend euismod arcu, non dapibus leo varius et. Mauris eu lacinia nulla. Aliquam suscipit pulvinar mattis. Aliquam sed tincidunt nunc, at cursus justo.", "https://images.pexels.com/photos/266176/pexels-photo-266176.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260"),

("Projeto 6","Lorem ipsum dolor sit amet","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget pulvinar nisi. In tellus augue, posuere non massa eget, molestie dictum velit. Phasellus gravida augue metus, sit amet bibendum lorem ullamcorper sit amet. Mauris dui arcu, placerat vel iaculis non, sodales at sapien. In convallis libero sed orci convallis elementum. Sed id consectetur sem. Etiam ultrices ante a porta vehicula. Donec sem justo, viverra sit amet finibus eu, condimentum quis mi. In eu dolor leo. Sed lacus nibh, faucibus vel orci in, luctus condimentum sem.

Donec nec lectus suscipit, aliquet dui et, porta sem. Nunc sit amet blandit massa, vitae mollis magna. Nunc eget suscipit ligula, non auctor nulla. Donec dui dui, posuere ac volutpat id, consequat in tellus. Donec quis nibh in enim tristique commodo in ut orci. Etiam convallis turpis venenatis odio imperdiet, at hendrerit elit feugiat. Curabitur nec bibendum erat, eu mollis libero. Quisque a est id elit tempor porttitor ullamcorper at mauris. Vivamus rutrum, diam sit amet vestibulum auctor, est felis suscipit ligula, vitae convallis dolor diam sit amet mauris. Nullam ac eros nec nibh sollicitudin rhoncus. Nunc tempor ornare vehicula. Duis vehicula lectus eget diam convallis placerat. Donec tellus risus, tempor id posuere nec, luctus nec odio. Nulla nec commodo tortor.

Vivamus massa nisi, mattis a venenatis et, gravida vulputate lectus. Aliquam nec lobortis ligula. Mauris ullamcorper vehicula dui in varius. Sed orci eros, tempus non arcu eu, dignissim aliquam sem. Integer tempus fermentum lectus, non volutpat massa bibendum nec. Vestibulum in mi quis sem auctor luctus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam eleifend euismod arcu, non dapibus leo varius et. Mauris eu lacinia nulla. Aliquam suscipit pulvinar mattis. Aliquam sed tincidunt nunc, at cursus justo.", "https://images.pexels.com/photos/256219/pexels-photo-256219.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260"),

("Projeto 7","Lorem ipsum dolor sit amet","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget pulvinar nisi. In tellus augue, posuere non massa eget, molestie dictum velit. Phasellus gravida augue metus, sit amet bibendum lorem ullamcorper sit amet. Mauris dui arcu, placerat vel iaculis non, sodales at sapien. In convallis libero sed orci convallis elementum. Sed id consectetur sem. Etiam ultrices ante a porta vehicula. Donec sem justo, viverra sit amet finibus eu, condimentum quis mi. In eu dolor leo. Sed lacus nibh, faucibus vel orci in, luctus condimentum sem.

Donec nec lectus suscipit, aliquet dui et, porta sem. Nunc sit amet blandit massa, vitae mollis magna. Nunc eget suscipit ligula, non auctor nulla. Donec dui dui, posuere ac volutpat id, consequat in tellus. Donec quis nibh in enim tristique commodo in ut orci. Etiam convallis turpis venenatis odio imperdiet, at hendrerit elit feugiat. Curabitur nec bibendum erat, eu mollis libero. Quisque a est id elit tempor porttitor ullamcorper at mauris. Vivamus rutrum, diam sit amet vestibulum auctor, est felis suscipit ligula, vitae convallis dolor diam sit amet mauris. Nullam ac eros nec nibh sollicitudin rhoncus. Nunc tempor ornare vehicula. Duis vehicula lectus eget diam convallis placerat. Donec tellus risus, tempor id posuere nec, luctus nec odio. Nulla nec commodo tortor.

Vivamus massa nisi, mattis a venenatis et, gravida vulputate lectus. Aliquam nec lobortis ligula. Mauris ullamcorper vehicula dui in varius. Sed orci eros, tempus non arcu eu, dignissim aliquam sem. Integer tempus fermentum lectus, non volutpat massa bibendum nec. Vestibulum in mi quis sem auctor luctus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam eleifend euismod arcu, non dapibus leo varius et. Mauris eu lacinia nulla. Aliquam suscipit pulvinar mattis. Aliquam sed tincidunt nunc, at cursus justo.", "https://images.pexels.com/photos/1260309/pexels-photo-1260309.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260"),

("Projeto 8","Lorem ipsum dolor sit amet","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget pulvinar nisi. In tellus augue, posuere non massa eget, molestie dictum velit. Phasellus gravida augue metus, sit amet bibendum lorem ullamcorper sit amet. Mauris dui arcu, placerat vel iaculis non, sodales at sapien. In convallis libero sed orci convallis elementum. Sed id consectetur sem. Etiam ultrices ante a porta vehicula. Donec sem justo, viverra sit amet finibus eu, condimentum quis mi. In eu dolor leo. Sed lacus nibh, faucibus vel orci in, luctus condimentum sem.

Donec nec lectus suscipit, aliquet dui et, porta sem. Nunc sit amet blandit massa, vitae mollis magna. Nunc eget suscipit ligula, non auctor nulla. Donec dui dui, posuere ac volutpat id, consequat in tellus. Donec quis nibh in enim tristique commodo in ut orci. Etiam convallis turpis venenatis odio imperdiet, at hendrerit elit feugiat. Curabitur nec bibendum erat, eu mollis libero. Quisque a est id elit tempor porttitor ullamcorper at mauris. Vivamus rutrum, diam sit amet vestibulum auctor, est felis suscipit ligula, vitae convallis dolor diam sit amet mauris. Nullam ac eros nec nibh sollicitudin rhoncus. Nunc tempor ornare vehicula. Duis vehicula lectus eget diam convallis placerat. Donec tellus risus, tempor id posuere nec, luctus nec odio. Nulla nec commodo tortor.

Vivamus massa nisi, mattis a venenatis et, gravida vulputate lectus. Aliquam nec lobortis ligula. Mauris ullamcorper vehicula dui in varius. Sed orci eros, tempus non arcu eu, dignissim aliquam sem. Integer tempus fermentum lectus, non volutpat massa bibendum nec. Vestibulum in mi quis sem auctor luctus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam eleifend euismod arcu, non dapibus leo varius et. Mauris eu lacinia nulla. Aliquam suscipit pulvinar mattis. Aliquam sed tincidunt nunc, at cursus justo.", "https://images.pexels.com/photos/1383834/pexels-photo-1383834.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260");